# Generated by Django 5.2.7 on 2025-10-29 16:05

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumerequest',
            name='experience',
            field=models.TextField(blank=True, verbose_name='Опыт'),
        ),
        migrations.AddField(
            model_name='resumerequest',
            name='job_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='resumerequest',
            name='skills',
            field=models.TextField(blank=True, verbose_name='Навыки'),
        ),
        migrations.AlterField(
            model_name='resumerequest',
            name='achievements',
            field=models.TextField(verbose_name='Достижения'),
        ),
        migrations.AlterField(
            model_name='resumerequest',
            name='employers',
            field=models.TextField(verbose_name='Работодатели'),
        ),
        migrations.AlterField(
            model_name='resumerequest',
            name='images',
            field=models.ManyToManyField(blank=True, to='core.userimage', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='resumerequest',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.resume_file_path, verbose_name='Файл (DOCX)'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_resume_format',
            field=models.CharField(choices=[('docx', 'DOCX'), ('pdf', 'PDF')], default='docx', max_length=10),
        ),
    ]
